import type { Metadata } from "next";
import { Poppins, Bebas_Neue } from "next/font/google";
import "./globals.css";
import { createClientComponentClient } from "@supabase/auth-helpers-nextjs";
import { useEffect, useState } from "react";

const poppins = Poppins({
  variable: "--font-sans",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

const bebas = Bebas_Neue({
  variable: "--font-display",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // small client check to ensure session refresh via middleware
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${bebas.variable} antialiased`}
      >
        <HeaderBar />
        {children}
      </body>
    </html>
  );
}

function HeaderBar() {
  "use client";
  const supabase = createClientComponentClient();
  const [email, setEmail] = useState<string | null>(null);
  useEffect(() => {
    supabase.auth.getUser().then(({ data }) => setEmail(data.user?.email ?? null));
  }, []);
  return (
    <header className="w-full flex items-center justify-end p-3 text-zinc-200">
      {email ? (
        <div className="flex items-center gap-3">
          <span className="text-sm">{email}</span>
          <button
            className="rounded-lg border border-white/15 px-3 py-1 hover:bg-white/5"
            onClick={async () => {
              await supabase.auth.signOut();
              location.href = "/";
            }}
          >
            Salir
          </button>
        </div>
      ) : (
        <div className="flex items-center gap-3">
          <a className="underline" href="/login">Ingresar</a>
          <a className="underline" href="/register">Registrarse</a>
        </div>
      )}
    </header>
  );
}
